<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVxliWOh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVxliWOh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVxliWOh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVxliWOh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVxliWOh\App_KernelDevDebugContainer([
    'container.build_hash' => 'VxliWOh',
    'container.build_id' => 'bce3884c',
    'container.build_time' => 1729435387,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVxliWOh');
